import { config, serviceUrl, ServiceName } from './config.js';
import { attributes, contents, datasources, namespaces, rules, treatmentMaps } from './domain.js';

export class DependencyError extends Error{constructor(public code:'DEPENDENCY_UNAVAILABLE'|'TIMEOUT'|'RATE_LIMITED'|'NOT_FOUND'|'FORBIDDEN'|'INTERNAL',message:string){super(message);}}
type RequestOptions={method?:'GET'|'POST';body?:unknown;signal?:AbortSignal};
async function request<T>(service:ServiceName,path:string,options:RequestOptions={}):Promise<T>{
 const base=serviceUrl(service);if(!base)throw new DependencyError('DEPENDENCY_UNAVAILABLE',`${service} service is not configured`);
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),config.SERVICE_TIMEOUT_MS);const abort=()=>controller.abort();options.signal?.addEventListener('abort',abort,{once:true});
 try{const response=await fetch(new URL(path,base.endsWith('/')?base:`${base}/`),{method:options.method??'GET',headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(config.PLATFORM_API_TOKEN?{authorization:`Bearer ${config.PLATFORM_API_TOKEN}`}:{})},body:options.body?JSON.stringify(options.body):undefined,signal:controller.signal});if(response.status===401||response.status===403)throw new DependencyError('FORBIDDEN','The service denied this authorized request');if(response.status===404)throw new DependencyError('NOT_FOUND','The requested entity was not found');if(response.status===429)throw new DependencyError('RATE_LIMITED','The service rate limit was reached');if(!response.ok)throw new DependencyError('INTERNAL',`The service returned HTTP ${response.status}`);return await response.json() as T;}catch(error){if(error instanceof DependencyError)throw error;if(controller.signal.aborted)throw new DependencyError('TIMEOUT',`${service} service timed out`);throw new DependencyError('DEPENDENCY_UNAVAILABLE',`${service} service is unavailable`);}finally{clearTimeout(timer);options.signal?.removeEventListener('abort',abort);}
}
const unwrap=<T>(value:any):T=>value?.data??value?.items??value?.results??value;
export const platform={
 async searchDataDictionary(query:string,limit:number,signal?:AbortSignal){if(config.DATA_MODE==='demo')return attributes.slice(0,limit).map(a=>({id:`${a.datasource}.${a.id}`,logicalName:a.title,physicalName:a.name,datasource:a.datasource,namespace:a.namespace,description:a.description,dataType:a.dataType,status:'ACTIVE',sourceVersion:a.version}));return unwrap<any[]>(await request('dataDictionary','v1/data-elements/search',{method:'POST',body:{query,limit},signal}));},
 async getDatasource(id:string,signal?:AbortSignal){if(config.DATA_MODE==='demo')return datasources.find(x=>x.id===id);return unwrap<any>(await request('dataDictionary',`v1/datasources/${encodeURIComponent(id)}`,{signal}));},
 async getNamespace(id:string,signal?:AbortSignal){if(config.DATA_MODE==='demo')return namespaces.find(x=>x.id===id);return unwrap<any>(await request('dataDictionary',`v1/namespaces/${encodeURIComponent(id)}`,{signal}));},
 async searchGlossary(query:string,limit:number,signal?:AbortSignal){if(config.DATA_MODE==='demo')return attributes.slice(0,limit);return unwrap<any[]>(await request('glossary','v1/attributes/search',{method:'POST',body:{query,limit},signal}));},
 async searchRules(query:string,limit:number,signal?:AbortSignal){if(config.DATA_MODE==='demo')return rules.slice(0,limit);return unwrap<any[]>(await request('rules','v1/rules/search',{method:'POST',body:{query,limit,status:['APPROVED']},signal}));},
 async getRuleGraph(ruleId:string,maxDepth:number,signal?:AbortSignal){if(config.DATA_MODE==='demo'){const root=rules.find(x=>x.id===ruleId)??rules[0];return{root,nodes:[root],edges:[],warnings:[]};}return unwrap<any>(await request('rules',`v1/rules/${encodeURIComponent(ruleId)}/graph?maxDepth=${maxDepth}`,{signal}));},
 async findSimilarRules(query:string,limit:number,signal?:AbortSignal){if(config.DATA_MODE==='demo')return rules.slice(0,limit).map(r=>({...r,signals:['SEMANTIC','ATTRIBUTE_OVERLAP'],logicalEquivalence:false}));return unwrap<any[]>(await request('rules','v1/rules/similarity',{method:'POST',body:{query,limit},signal}));},
 async findHistoricalContent(query:string,limit:number,signal?:AbortSignal){if(config.DATA_MODE==='demo')return contents.slice(0,limit);return unwrap<any[]>(await request('content','v1/content/search-similar',{method:'POST',body:{text:query,limit,status:['APPROVED'],associations:['APPROVED']},signal}));},
 async recommend(input:unknown,signal?:AbortSignal){if(config.DATA_MODE==='demo')return{rules:rules.slice(0,5).map(r=>({ruleId:r.id,ruleVersion:r.version,name:r.title,score:r.score,historicalSupportCount:r.historicalSupportCount,dependencies:[],attributeUses:[]})),attributes:attributes.map(a=>({attributeId:a.id,score:a.score,usageStatus:a.usage,historicalUsageCount:a.historicalUsageCount,ruleEvidence:[]})),modelVersion:'demo-baseline',indexVersion:'demo-1'};return unwrap<any>(await request('ml','v1/recommend',{method:'POST',body:input,signal}));},
 async getTreatmentMap(id:string,signal?:AbortSignal){if(config.DATA_MODE==='demo')return treatmentMaps.find(x=>x.id===id)??treatmentMaps[0];return unwrap<any>(await request('treatment',`v1/treatment-maps/${encodeURIComponent(id)}`,{signal}));},
 async validateRule(condition:unknown,signal?:AbortSignal){return unwrap<any>(await request('ccre','v1/rules/validate',{method:'POST',body:{condition},signal}));},
 async executeRuleTests(condition:unknown,tests:unknown[],signal?:AbortSignal){return unwrap<any>(await request('ccre','v1/rules/test',{method:'POST',body:{condition,tests},signal}));},
 async createDraft(type:'rule'|'treatment-map',payload:unknown,idempotencyKey:string,signal?:AbortSignal){return unwrap<any>(await request(type==='rule'?'rules':'treatment',`v1/${type==='rule'?'rules':'treatment-maps'}/drafts`,{method:'POST',body:{payload,idempotencyKey},signal}));}
};
