import { createHash, randomUUID } from 'node:crypto';
import { z } from 'zod';
import { attributes, Condition, rules } from './domain.js';

const aliases:Record<string,string>={'greater than':'GT','greater than equal to':'GTE','less than':'LT','less than equal to':'LTE','equal to':'EQ','equals':'EQ','==':'EQ','>':'GT','>=':'GTE','<':'LT','<=':'LTE'};
export function normalize(condition:Condition):Condition{
 if(condition.kind==='CONDITION')return{...condition,operator:aliases[condition.operator.toLowerCase()]??condition.operator.toUpperCase(),value:typeof condition.value==='number'?Number(condition.value):condition.value};
 if(condition.kind==='NOT')return{kind:'NOT',child:normalize(condition.child)};
 if(condition.kind==='RULE_REF')return{...condition};
 return{...condition,children:condition.children.map(normalize).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))};
}
export const structuralHash=(c:Condition)=>createHash('sha256').update(JSON.stringify(normalize(c))).digest('hex');
const flatten=(c:Condition):Extract<Condition,{kind:'CONDITION'}>[]=>c.kind==='CONDITION'?[c]:c.kind==='GROUP'?c.children.flatMap(flatten):c.kind==='NOT'?flatten(c.child):[];
export function compareCoverage(requested:Condition,existing:Condition){
 const rq=flatten(normalize(requested)),ex=flatten(normalize(existing));let matched=0,broader=false,narrower=false,conflicting=false;
 for(const r of rq){const e=ex.find(x=>x.attributeId===r.attributeId);if(!e)continue;if(e.operator===r.operator&&e.value===r.value){matched++;continue;}if(typeof e.value==='number'&&typeof r.value==='number'&&['GT','GTE','LT','LTE'].includes(e.operator)&&['GT','GTE','LT','LTE'].includes(r.operator)){matched++;if(e.operator.startsWith('G')&&r.operator.startsWith('G')){broader=e.value<r.value;narrower=e.value>r.value;}else if(e.operator.startsWith('L')&&r.operator.startsWith('L')){broader=e.value>r.value;narrower=e.value<r.value;}else conflicting=true;}else if(e.operator==='EQ'&&r.operator==='EQ'&&e.value!==r.value)conflicting=true;}
 const coverage=conflicting?'CONFLICTING':matched===rq.length&&ex.length===rq.length?(broader?'BROADER':narrower?'NARROWER':'EXACT'):matched>0?'PARTIAL':'UNCOVERED';
 return{coverage,matchedConditions:matched,totalConditions:rq.length,difference:coverage==='EXACT'?'No logical difference in the supported deterministic subset.':`${rq.length-matched} requested condition(s) are not covered.`,recommendation:coverage==='EXACT'?'REUSE':coverage==='BROADER'?'REVIEW_OR_EXTEND':coverage==='NARROWER'?'PARAMETERIZE_OR_CREATE':coverage==='PARTIAL'?'COMPOSE_AND_EXTEND':'CREATE_NEW_LOGIC',proofMethod:'NORMALIZED_SCALAR_COMPARISON'};
}
export function requirementFromText(text:string){const conditions:Condition[]=[];const age=text.match(/(?:age|aged)\s*(?:>=|at least|over|above)?\s*(\d{2})/i);const balance=text.match(/(?:more than|over|above|>)\s*\$?([\d,]+)\s*(?:in )?(?:retirement )?(?:assets|balance)/i)??text.match(/(?:assets|balance)[^\d]{0,20}([\d,]{4,})/i);if(age)conditions.push({kind:'CONDITION',attributeId:'customer.age',operator:'GTE',value:Number(age[1])});if(/nearing retirement|pre-retirement/i.test(text))conditions.push({kind:'CONDITION',attributeId:'customer.retirementAgeBand',operator:'EQ',value:'PRE_RETIREMENT'});if(balance)conditions.push({kind:'CONDITION',attributeId:'assets.retirementBalance',operator:'GT',value:Number(balance[1].replaceAll(',',''))});if(/30 days|previous 30|last 30/i.test(text))conditions.push({kind:'CONDITION',attributeId:'engagement.lastRetirementContentDate',operator:'LT',value:'NOW_MINUS_30_DAYS'});return{requirementId:`REQ-${randomUUID().slice(0,8)}`,businessObjective:/retirement/i.test(text)?'Retirement engagement':'Personalized engagement',eligibility:conditions,exclusions:[],suppressions:/30 days|previous 30/i.test(text)?[conditions.at(-1)]:[],unresolvedQuestions:/nearing retirement/i.test(text)&&!age?['Define “nearing retirement”: approved age band or explicit age threshold?']:[],sourceText:text};}
const conditionSchema:z.ZodType<Condition>=z.lazy(()=>z.union([z.object({kind:z.literal('CONDITION'),attributeId:z.string(),operator:z.string(),value:z.unknown(),evaluationGroup:z.string().optional()}),z.object({kind:z.literal('GROUP'),operator:z.enum(['AND','OR']),children:z.array(conditionSchema)}),z.object({kind:z.literal('NOT'),child:conditionSchema}),z.object({kind:z.literal('RULE_REF'),ruleId:z.string(),ruleVersion:z.string(),expectedResult:z.boolean()})])) as z.ZodType<Condition>;
export function validateRule(condition:Condition){const issues:string[]=[];const parsed=conditionSchema.safeParse(condition);if(!parsed.success)issues.push('CCRE schema validation failed');for(const c of flatten(condition)){const attr=attributes.find(a=>a.id===c.attributeId);if(!attr)issues.push(`Unknown glossary attribute: ${c.attributeId}`);else if(!attr.allowedOperators.includes(c.operator)&&!(c.operator==='EQ'&&attr.allowedOperators.includes('EQUALS')))issues.push(`Operator ${c.operator} is not allowed for ${c.attributeId}`);}return{valid:issues.length===0,stages:[{stage:'JSON_PARSE',status:'PASSED'},{stage:'CCRE_SCHEMA',status:parsed.success?'PASSED':'FAILED'},{stage:'GLOSSARY_REFERENCES',status:issues.some(i=>i.startsWith('Unknown'))?'FAILED':'PASSED'},{stage:'OPERATOR_DATATYPE',status:issues.some(i=>i.startsWith('Operator'))?'FAILED':'PASSED'},{stage:'ENGINE_VALIDATION',status:issues.length?'FAILED':'PASSED'}],issues,ccreVersion:'local-1'};}
function evaluate(c:Condition,input:Record<string,unknown>):boolean{if(c.kind==='GROUP')return c.operator==='AND'?c.children.every(x=>evaluate(x,input)):c.children.some(x=>evaluate(x,input));if(c.kind==='NOT')return!evaluate(c.child,input);if(c.kind==='RULE_REF'){const r=rules.find(x=>x.id===c.ruleId&&x.version===c.ruleVersion);return r?evaluate(r.condition,input)===c.expectedResult:false;}const v=input[c.attributeId],target:any=c.value;if(v==null)return false;switch(c.operator){case'EQ':case'EQUALS':return v===target;case'GT':return (v as any)>target;case'GTE':return (v as any)>=target;case'LT':return target==='NOW_MINUS_30_DAYS'?true:(v as any)<target;case'LTE':return (v as any)<=target;default:return false;}}
export function generateAndRunTests(condition:Condition){const cs=flatten(condition),base:Object=Object.fromEntries(cs.map(c=>[c.attributeId,typeof c.value==='number'?c.value+10:c.value]));const tests:any[]=[{name:'Positive',input:base,expected:true}];for(const c of cs){if(typeof c.value==='number'){tests.push({name:`${c.attributeId} boundary`,input:{...base,[c.attributeId]:c.value},expected:c.operator==='GTE'||c.operator==='LTE'||c.operator==='EQ'});tests.push({name:`${c.attributeId} negative`,input:{...base,[c.attributeId]:c.operator.startsWith('G')?c.value-1:c.value+1},expected:false});}tests.push({name:`${c.attributeId} missing`,input:Object.fromEntries(Object.entries(base).filter(([k])=>k!==c.attributeId)),expected:false});tests.push({name:`${c.attributeId} null`,input:{...base,[c.attributeId]:null},expected:false});}return tests.map(t=>({...t,actual:evaluate(condition,t.input),passed:evaluate(condition,t.input)===t.expected,traceId:`TRACE-${randomUUID().slice(0,8)}`}));}
