export type Scope = 'IN_SCOPE' | 'SUPPORTING_CONTEXT' | 'AMBIGUOUS' | 'OUT_OF_SCOPE' | 'DISALLOWED';
export type Intent = 'DISCOVER_GLOSSARY'|'DISCOVER_RULES'|'ANALYZE_CONTENT'|'RECOMMEND'|'EXPLAIN_DECISION'|'PROPOSE_RULE'|'PROPOSE_TREATMENT';
export type OperationClass = 'READ'|'ANALYZE'|'SIMULATE';
export interface Principal { userId:string; roles:string[]; businessUnitIds:string[]; teamIds:string[]; }
export interface Conversation { id:string; version:number; ownerUserId:string; businessUnitId:string; owningTeamId?:string; visibility:'PRIVATE'|'TEAM'|'BUSINESS_UNIT'; status:'ACTIVE'|'ARCHIVED'; title:string; summary?:string; scopeState:Record<string,unknown>; createdAt:string; updatedAt:string; }
export interface Evidence { id:string; entityType:string; entityId:string; entityVersion:string; relationship:string; sourceSystem:string; label:string; }
export interface Card { id:string; cardType:string; schemaVersion:string; eyebrow:string; title:string; description:string; score?:number; confidence?:string; status?:string; tags?:string[]; evidence?:Evidence[]; choices?:string[]; data?:unknown; securitySensitive?:boolean; }

export const datasources=[{id:'CUSTOMER_PROFILE',name:'Customer Profile',description:'Authoritative customer demographics',status:'ACTIVE'},{id:'WEALTH_ASSETS',name:'Wealth Assets',description:'Authorized account and balance data',status:'ACTIVE'},{id:'ENGAGEMENT',name:'Engagement History',description:'Content delivery and response history',status:'ACTIVE'}];
export const namespaces=[{id:'customer',datasource:'CUSTOMER_PROFILE',description:'Core customer profile',primaryKeys:['customerId']},{id:'assets',datasource:'WEALTH_ASSETS',description:'Aggregated authorized asset data',primaryKeys:['customerId']},{id:'engagement',datasource:'ENGAGEMENT',description:'Customer communication history',primaryKeys:['customerId']}];
export const attributes = [
  { id:'customer.retirementAgeBand', datasource:'CUSTOMER_PROFILE', namespace:'customer', name:'retirementAgeBand', title:'Retirement age band', description:'Customer proximity to their planned or standard retirement age.', dataType:'string', allowedOperators:['EQUALS','IN'], aliases:['nearing retirement','pre-retirement'], confidence:'High', score:.94, status:'APPROVED', version:'12', usage:'USED', historicalUsageCount:8 },
  { id:'customer.age', datasource:'CUSTOMER_PROFILE', namespace:'customer', name:'age', title:'Customer age', description:'Current customer age in completed years. A threshold must be supplied by the user.', dataType:'integer', allowedOperators:['EQ','GT','GTE','LT','LTE'], aliases:['years old','customer age'], confidence:'High', score:.91, status:'APPROVED', version:'12', usage:'USED', historicalUsageCount:23 },
  { id:'assets.retirementBalance', datasource:'WEALTH_ASSETS', namespace:'assets', name:'retirementBalance', title:'Retirement asset balance', description:'Total current value of authorized retirement accounts in base currency.', dataType:'number', allowedOperators:['EQ','GT','GTE','LT','LTE'], aliases:['retirement assets','pension balance'], confidence:'High', score:.97, status:'APPROVED', version:'9', usage:'USED', historicalUsageCount:12 },
  { id:'engagement.lastRetirementContentDate', datasource:'ENGAGEMENT', namespace:'engagement', name:'lastRetirementContentDate', title:'Last retirement content date', description:'Most recent date on which retirement-planning content was delivered.', dataType:'date', allowedOperators:['GT','GTE','LT','LTE'], aliases:['last retirement contact','cooling period'], confidence:'Medium', score:.86, status:'APPROVED', version:'4', usage:'NEVER_USED', historicalUsageCount:0 }
];
export type Condition={kind:'CONDITION';attributeId:string;operator:string;value:unknown;evaluationGroup?:string}|{kind:'GROUP';operator:'AND'|'OR';children:Condition[]}|{kind:'NOT';child:Condition}|{kind:'RULE_REF';ruleId:string;ruleVersion:string;expectedResult:boolean};
export const rules = [
  { id:'RULE-RET-014', version:'7', title:'High-value pre-retirement audience', description:'Customers in a pre-retirement age band with retirement assets above 200,000.', status:'APPROVED', score:.92, historicalSupportCount:14, condition:{kind:'GROUP',operator:'AND',children:[{kind:'CONDITION',attributeId:'customer.retirementAgeBand',operator:'EQUALS',value:'PRE_RETIREMENT'},{kind:'CONDITION',attributeId:'assets.retirementBalance',operator:'GT',value:200000}]} as Condition },
  { id:'RULE-RET-031', version:'3', title:'Retirement content cooling period', description:'Suppresses retirement-planning content when delivered in the previous 30 days.', status:'APPROVED', score:.89, historicalSupportCount:22, condition:{kind:'CONDITION',attributeId:'engagement.lastRetirementContentDate',operator:'LT',value:'NOW_MINUS_30_DAYS'} as Condition },
  { id:'RULE-WLT-008', version:'11', title:'High retirement asset balance', description:'Customers whose retirement asset balance exceeds 250,000.', status:'APPROVED', score:.84, historicalSupportCount:9, condition:{kind:'CONDITION',attributeId:'assets.retirementBalance',operator:'GT',value:250000} as Condition },
  { id:'RULE-RET-COMPOSED', version:'2', title:'Retirement consolidation audience', description:'Composes age, asset and contact-policy rules.', status:'APPROVED', score:.96, historicalSupportCount:6, condition:{kind:'GROUP',operator:'AND',children:[{kind:'RULE_REF',ruleId:'RULE-RET-014',ruleVersion:'7',expectedResult:true},{kind:'RULE_REF',ruleId:'RULE-RET-031',ruleVersion:'3',expectedResult:true}]} as Condition }
];
export const contents=[
 {id:'CONTENT-9001',version:'3',title:'Bring your retirement savings together',text:'Consolidate old workplace retirement accounts for a clearer view of your future.',status:'APPROVED',ruleIds:['RULE-RET-014','RULE-RET-031'],score:.94},
 {id:'CONTENT-8140',version:'5',title:'Prepare for the next chapter',text:'Approaching retirement? See your savings and options in one place.',status:'APPROVED',ruleIds:['RULE-RET-COMPOSED'],score:.88}
];
export const treatmentMaps=[{id:'TMAP-RET-01',version:'4',name:'Retirement consolidation treatment',contentId:'CONTENT-9001',ruleId:'RULE-RET-COMPOSED',priority:40,channel:'WEB',status:'APPROVED'}];
