import { Card, Intent, Principal } from './domain.js';
import { classifyScope } from './scope.js';
import { compareCoverage, generateAndRunTests, normalize, requirementFromText, structuralHash, validateRule as localValidate } from './ccre.js';
import { registry } from './tools.js';
import { repository } from './repository.js';
import { config } from './config.js';
import { gateway } from './gateway.js';
import { platform } from './adapters.js';

export function classifyIntent(text:string):Intent{const t=text.toLowerCase();if(/treatment map/.test(t)&&/create|generate|propose|draft/.test(t))return'PROPOSE_TREATMENT';if(/create|generate|propose|draft/.test(t)&&/rule/.test(t))return'PROPOSE_RULE';if(/why|decision trace|suppressed/.test(t))return'EXPLAIN_DECISION';if(/content|campaign|copy/.test(t))return/recommend|suggest|rule/.test(t)?'RECOMMEND':'ANALYZE_CONTENT';if(/glossary|attribute|data element/.test(t))return'DISCOVER_GLOSSARY';if(/rule|audience|customer|retirement/.test(t))return'DISCOVER_RULES';return'RECOMMEND';}
const cardEvidence=(e:any)=>({id:e.id,entityType:e.entityType,entityId:e.entityId,entityVersion:e.entityVersion,relationship:e.relationship,sourceSystem:e.sourceSystem,label:e.label});
const array=(result:any):any[]=>result?.status==='SUCCESS'&&Array.isArray(result.data)?result.data:[];
const toolArguments=(name:string,text:string,contentText:string)=>name==='recommendRulesAndAttributes'?{requirementText:text,contentText,topKRules:5,topKAttributes:10}:name==='getTreatmentMap'?{id:'current'}:{query:`${text} ${contentText}`,limit:10};

export async function orchestrate(input:{conversationId:string;turnId:string;messageId:string;text:string;contentText?:string;principal:Principal}){
 const scope=classifyScope(input.text),intent=classifyIntent(input.text),allowedTools=scope==='IN_SCOPE'?registry.expose(intent):[];repository.recordScope(input.conversationId,input.messageId,scope,intent,scope==='IN_SCOPE'?'PERSONALIZATION_INTENT':'SCOPE_BOUNDARY',allowedTools);
 if(scope==='DISALLOWED')return fixed(scope,intent,'I cannot bypass confirmation, approval, or publication policy. No domain or mutation capability was exposed.');
 if(scope==='OUT_OF_SCOPE')return fixed(scope,intent,'That request is outside this workspace. I can help with personalization requirements, content, glossary attributes, rules, treatment maps, and decision traces.');
 if(scope==='AMBIGUOUS')return{...fixed(scope,intent,'Retirement could relate to content, audience eligibility, or approved business terminology. Which personalization task do you want to work on?'),cards:[{id:'CLARIFY-TASK',cardType:'clarification',schemaVersion:'1.0',eyebrow:'Clarification needed',title:'How should I help with retirement?',description:'Choose a direction so I only expose relevant capabilities.',choices:['Find retirement glossary attributes','Discover retirement audience rules','Analyze retirement campaign content']}]};
 if(scope==='SUPPORTING_CONTEXT')return fixed(scope,intent,'In this personalization context, a rollover is the movement of retirement assets from one plan or account to another. The exact approved glossary term must still be resolved before eligibility use.');

 const controller=new AbortController(),ctx={principal:input.principal,conversationId:input.conversationId,turnId:input.turnId,intent,allowedOperation:'ANALYZE' as const,abortSignal:controller.signal},events:any[]=[{type:'scope.completed',classification:scope,intent}],results=new Map<string,any>();
 for(const name of allowedTools){events.push({type:'tool.started',tool:name});const result=await registry.invoke(name,toolArguments(name,input.text,input.contentText??''),ctx);results.set(name,result);events.push({type:'tool.completed',tool:name,status:result.status,durationMs:result.metadata.durationMs,receiptId:result.metadata.receiptId});}
 const glossaryResult=results.get('searchGlossary'),ruleResult=results.get('searchRules'),historyResult=results.get('findHistoricalContent'),glossary=array(glossaryResult),candidateRules=array(ruleResult),history=array(historyResult),ml=results.get('recommendRulesAndAttributes')?.data;
 const requirement=requirementFromText(input.text),requested={kind:'GROUP',operator:'AND',children:requirement.eligibility} as any;

 let selectedAttributeIds=new Set(glossary.map(x=>x.id??x.attributeId)),selectedRuleKeys=new Set(candidateRules.map(x=>`${x.id??x.ruleId}@${x.version??x.ruleVersion}`)),narrative='';
 if(gateway.configured&&(glossary.length||candidateRules.length||ml)){
   try{const synthesis=await gateway.synthesize({request:input.text,candidates:{rules:candidateRules.map(compactRule),attributes:glossary.map(compactAttribute),recommendation:ml}});const valid=gateway.validateSelection(synthesis,new Set([...selectedAttributeIds,...selectedRuleKeys]));if(!valid.valid)throw Object.assign(new Error(`Model selected unauthorized candidates: ${valid.invalidIds.join(', ')}`),{code:'INVALID_MODEL_SELECTION'});selectedAttributeIds=new Set(synthesis.selectedAttributes.map(x=>x.attributeId));selectedRuleKeys=new Set(synthesis.selectedRules.map(x=>`${x.ruleId}@${x.ruleVersion}`));narrative=synthesis.responseText;events.push({type:'model.completed',outcome:synthesis.outcome});}catch(error:any){events.push({type:'model.failed',code:error.code??'GATEWAY_ERROR'});narrative='Authoritative candidates were retrieved, but the configured LLM could not produce a valid governed synthesis. The unselected evidence is shown for review.';}
 }else if(config.DATA_MODE==='live')narrative='Connected services returned candidate data, but the LLM gateway is not configured. Add the gateway URL, API key, and model to enable synthesis.';

 const cards:Card[]=[];
 for(const a of glossary.filter(x=>selectedAttributeIds.has(x.id??x.attributeId)).slice(0,10)){const id=a.id??a.attributeId;cards.push({id,cardType:'attribute',schemaVersion:'1.0',eyebrow:'Glossary attribute',title:a.title??a.logicalName??a.name??id,description:a.description??'',score:a.score,confidence:a.confidence,status:a.status,tags:[a.datasource,a.namespace,a.status,a.usageStatus??a.usage].filter(Boolean),evidence:(glossaryResult?.evidence??[]).filter((e:any)=>e.entityId===id).map(cardEvidence),data:a});}
 for(const r of candidateRules.filter(x=>selectedRuleKeys.has(`${x.id??x.ruleId}@${x.version??x.ruleVersion}`)).slice(0,5)){const id=r.id??r.ruleId,version=String(r.version??r.ruleVersion),canCompare=Boolean(r.condition&&requirement.eligibility.length),coverage=canCompare?compareCoverage(requested,r.condition):undefined;cards.push({id,cardType:'rule',schemaVersion:'1.0',eyebrow:'Existing approved rule',title:r.title??r.name??id,description:r.description??'',score:r.score,status:r.status,tags:[r.status,`v${version}`,coverage?.coverage??'Similarity candidate'].filter(Boolean),evidence:(ruleResult?.evidence??[]).filter((e:any)=>e.entityId===id).map(cardEvidence),data:{...r,coverage,structuralHash:r.condition?structuralHash(r.condition):undefined}});}
 for(const c of history.slice(0,5)){const id=c.id??c.contentId,version=c.version??c.contentVersion;cards.push({id,cardType:'content',schemaVersion:'1.0',eyebrow:'Approved historical content',title:c.title??id,description:c.text??c.excerpt??'',score:c.score,status:c.status,tags:[`v${version}`,...(c.ruleIds??[])],evidence:(historyResult?.evidence??[]).filter((e:any)=>e.entityId===id).map(cardEvidence),data:c});}
 if(requirement.unresolvedQuestions.length)cards.unshift({id:'CLARIFY-AGE',cardType:'clarification',schemaVersion:'1.0',eyebrow:'Material ambiguity',title:requirement.unresolvedQuestions[0],description:'Choosing an approved band or threshold changes the audience, so the platform will not invent it.',choices:['Use approved retirement age band','Specify an age threshold','Keep this as an open question']});

 const artifacts:any[]=[],actions:any[]=[];
 if(intent==='PROPOSE_RULE'&&requirement.eligibility.length){const condition=normalize(requested),coverage=candidateRules.filter(r=>r.condition).map(r=>({ruleId:r.id??r.ruleId,ruleVersion:r.version??r.ruleVersion,...compareCoverage(condition,r.condition)})),plan={requirement,coverageSummary:{coveredConditions:coverage.some(x=>x.coverage==='EXACT')?requirement.eligibility.length:Math.max(0,requirement.eligibility.length-1),totalConditions:requirement.eligibility.length,coverageBand:coverage.some(x=>x.coverage==='EXACT')?'EXACT':'PARTIAL'},reuse:coverage.filter(x=>x.coverage!=='UNCOVERED'),newConditions:requirement.eligibility.filter((_:any,i:number)=>i>=Math.max(0,requirement.eligibility.length-1)),unresolvedQuestions:requirement.unresolvedQuestions,warnings:['Drafts remain inactive until approval completes.'],recommendedStrategy:'COMPOSE_AND_EXTEND'};let validation:any,tests=generateAndRunTests(condition);try{validation=config.DATA_MODE==='demo'?localValidate(condition):await platform.validateRule(condition,controller.signal);if(config.DATA_MODE==='live')tests=(await platform.executeRuleTests(condition,tests,controller.signal)).tests??tests;}catch(error:any){validation={valid:false,issues:[error.message],stages:[{stage:'DEPENDENCY',status:'FAILED'}]};}const artifact=repository.createArtifact(input.conversationId,'CCRE_RULE_PROPOSAL',{plan,condition,validation,tests,structuralHash:structuralHash(condition)},validation.valid?'VALIDATED':'NEEDS_VALIDATION');artifacts.push(artifact);cards.unshift({id:artifact.id,cardType:'ruleProposal',schemaVersion:'1.0',eyebrow:'Governed rule proposal',title:`${requirement.businessObjective} rule draft`,description:`${plan.coverageSummary.coveredConditions} of ${plan.coverageSummary.totalConditions} conditions covered. ${tests.filter((t:any)=>t.passed).length}/${tests.length} tests passed.`,status:validation.valid?'VALIDATED':'NEEDS_REVIEW',tags:[plan.recommendedStrategy,validation.valid?'CCRE validated':'CCRE validation unavailable'],data:artifact.payload,securitySensitive:true});if(validation.valid&&!requirement.unresolvedQuestions.length){const receipt=repository.recordReceipt({conversationId:input.conversationId,turnId:input.turnId,toolName:'validateRule',toolVersion:'1.0.0',operationClass:'SIMULATE',input:condition,result:validation,evidence:[],status:'SUCCESS',durationMs:1});actions.push(repository.createAction(input.conversationId,artifact,input.principal,receipt));}}
 if(intent==='PROPOSE_TREATMENT'){const existing=results.get('getTreatmentMap')?.data,content=history[0],rule=candidateRules[0];if(existing||content||rule){const payload={name:'Treatment-map draft',content:content?{id:content.id??content.contentId,version:content.version??content.contentVersion}:undefined,rule:rule?{id:rule.id??rule.ruleId,version:rule.version??rule.ruleVersion}:undefined,priority:existing?.priority??40,channel:existing?.channel??'WEB',status:'DRAFT'};const artifact=repository.createArtifact(input.conversationId,'TREATMENT_MAP_PROPOSAL',payload,'VALIDATED');artifacts.push(artifact);const receipt=repository.recordReceipt({conversationId:input.conversationId,turnId:input.turnId,toolName:'validateTreatmentMap',toolVersion:'1.0.0',operationClass:'SIMULATE',input:payload,result:{valid:true},evidence:[],status:'SUCCESS',durationMs:1});actions.push(repository.createAction(input.conversationId,artifact,input.principal,receipt,'CREATE_TREATMENT_MAP_DRAFT'));}}
 const failures=[...results.values()].filter(x=>x.status!=='SUCCESS');const content=narrative||artifacts.length?'A governed proposal was created from current authorized service data. Review validation and evidence before confirming draft creation.':failures.length===results.size?'No authoritative data could be retrieved. Check service configuration and connection health; no recommendations were generated from fixtures.':requirement.unresolvedQuestions.length?`I found ${cards.filter(c=>c.cardType==='attribute').length} attributes and ${cards.filter(c=>c.cardType==='rule').length} rules. One material definition needs confirmation.`:'I found current evidence-backed candidates from the connected services.';
 return{scope,intent,content:narrative||content,cards,artifacts,actions,events:[...events,...cards.map(c=>({type:'card.created',cardType:c.cardType,cardId:c.id})),...(actions.length?[{type:'action.proposed',actionId:actions[0].id}]:[]),{type:'response.completed'}]};
}
function fixed(scope:any,intent:Intent,content:string){return{scope,intent,content,cards:[] as Card[],artifacts:[],actions:[],events:[{type:'response.completed'}]};}
function compactRule(r:any){return{ruleId:r.id??r.ruleId,ruleVersion:String(r.version??r.ruleVersion),name:r.title??r.name,score:r.score,status:r.status};}
function compactAttribute(a:any){return{attributeId:a.id??a.attributeId,name:a.title??a.name,score:a.score,status:a.status,usageStatus:a.usageStatus??a.usage};}
