import { DatabaseSync } from 'node:sqlite';
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { Conversation, Principal, Scope } from './domain.js';

const dbPath=process.env['DATABASE_PATH'] ?? resolve('.data/pzn.sqlite');
mkdirSync(dirname(dbPath),{recursive:true});
export const db=new DatabaseSync(dbPath);
db.exec(`
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS conversations(id TEXT PRIMARY KEY, version INTEGER NOT NULL, owner_user_id TEXT NOT NULL, business_unit_id TEXT NOT NULL, owning_team_id TEXT, visibility TEXT NOT NULL, status TEXT NOT NULL, title TEXT NOT NULL, summary TEXT, scope_state TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, client_message_id TEXT, role TEXT NOT NULL, content TEXT NOT NULL, sequence_number INTEGER NOT NULL, scope TEXT, intent TEXT, include_in_context INTEGER NOT NULL, status TEXT NOT NULL, metadata TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(conversation_id,client_message_id), UNIQUE(conversation_id,sequence_number));
CREATE TABLE IF NOT EXISTS turns(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, base_version INTEGER NOT NULL, user_message_id TEXT NOT NULL, assistant_message_id TEXT, actor_user_id TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, error_code TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS one_running_turn ON turns(conversation_id) WHERE status='RUNNING';
CREATE TABLE IF NOT EXISTS scope_decisions(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, message_id TEXT NOT NULL, classification TEXT NOT NULL, intent TEXT, reason_code TEXT NOT NULL, allowed_tools TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, turn_id TEXT, tool_name TEXT NOT NULL, tool_version TEXT NOT NULL, operation_class TEXT NOT NULL, input_hash TEXT NOT NULL, result_hash TEXT, evidence TEXT NOT NULL, status TEXT NOT NULL, error_code TEXT, duration_ms INTEGER, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifacts(id TEXT NOT NULL, conversation_id TEXT NOT NULL, type TEXT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL, payload TEXT NOT NULL, payload_hash TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(id,version));
CREATE TABLE IF NOT EXISTS actions(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, type TEXT NOT NULL, artifact_id TEXT NOT NULL, artifact_version INTEGER NOT NULL, artifact_hash TEXT NOT NULL, status TEXT NOT NULL, expires_at TEXT NOT NULL, validation_receipt_id TEXT NOT NULL, owner_user_id TEXT NOT NULL, result TEXT, idempotency_key TEXT UNIQUE, created_at TEXT NOT NULL, executed_at TEXT);
CREATE TABLE IF NOT EXISTS decisions(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, type TEXT NOT NULL, payload TEXT NOT NULL, state TEXT NOT NULL, source_message_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS operations(id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, events TEXT NOT NULL, response TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL);
`);
const now=()=>new Date().toISOString(); export const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const parseConversation=(r:any):Conversation=>({id:r.id,version:r.version,ownerUserId:r.owner_user_id,businessUnitId:r.business_unit_id,owningTeamId:r.owning_team_id??undefined,visibility:r.visibility,status:r.status,title:r.title,summary:r.summary??undefined,scopeState:JSON.parse(r.scope_state),createdAt:r.created_at,updatedAt:r.updated_at});
export const repository={
 createConversation(principal:Principal,input:any={}){const id=`CONV-${randomUUID().slice(0,8).toUpperCase()}`,t=now();db.prepare('INSERT INTO conversations VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,1,principal.userId,input.businessUnitId??principal.businessUnitIds[0],input.owningTeamId??principal.teamIds[0],input.visibility??'PRIVATE','ACTIVE','New personalization conversation',null,JSON.stringify({allowedDomains:[],completedSteps:[],nextExpectedSteps:[]}),t,t);return this.getConversation(id)!;},
 getConversation(id:string){const r=db.prepare('SELECT * FROM conversations WHERE id=?').get(id);return r?parseConversation(r):undefined;},
 listConversations(principal:Principal){return (db.prepare('SELECT * FROM conversations WHERE owner_user_id=? ORDER BY updated_at DESC LIMIT 50').all(principal.userId) as any[]).map(parseConversation);},
 getMessages(id:string){return (db.prepare('SELECT * FROM messages WHERE conversation_id=? ORDER BY sequence_number').all(id) as any[]).map(r=>({...r,metadata:JSON.parse(r.metadata)}));},
 beginTurn(conversation:Conversation,principal:Principal,clientId:string,content:string,expected?:number){if(expected!==undefined&&expected!==conversation.version)throw Object.assign(new Error('Conversation version conflict'),{code:'CONFLICT'});const duplicate=db.prepare('SELECT * FROM messages WHERE conversation_id=? AND client_message_id=?').get(conversation.id,clientId) as any;if(duplicate)return {duplicate:true,message:duplicate};const seq=(db.prepare('SELECT COALESCE(MAX(sequence_number),0)+1 n FROM messages WHERE conversation_id=?').get(conversation.id) as any).n,id=`MSG-${randomUUID()}`,turnId=`TURN-${randomUUID()}`,t=now();db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,conversation.id,clientId,'user',content,seq,null,null,1,'PERSISTED','{}',t);db.prepare('INSERT INTO turns VALUES(?,?,?,?,?,?,?,?,?,?)').run(turnId,conversation.id,conversation.version,id,null,principal.userId,'RUNNING',t,null,null);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return {duplicate:false,messageId:id,turnId};},
 finalizeTurn(conversationId:string,turnId:string,content:string,scope:Scope,intent:string,cards:unknown[],extra:any={}){const c=this.getConversation(conversationId)!;const seq=(db.prepare('SELECT COALESCE(MAX(sequence_number),0)+1 n FROM messages WHERE conversation_id=?').get(conversationId) as any).n,id=`MSG-${randomUUID()}`,t=now();db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,conversationId,null,'assistant',content,seq,scope,intent,scope==='OUT_OF_SCOPE'||scope==='DISALLOWED'?0:1,'PERSISTED',JSON.stringify({cards,...extra}),t);db.prepare('UPDATE turns SET assistant_message_id=?,status=?,completed_at=? WHERE id=?').run(id,'COMPLETED',t,turnId);db.prepare('UPDATE conversations SET version=?,title=CASE WHEN title=? THEN ? ELSE title END,updated_at=? WHERE id=?').run(c.version+1,'New personalization conversation',content.slice(0,70),t,conversationId);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return {messageId:id,version:c.version+1};},
 recordScope(conversationId:string,messageId:string,scope:Scope,intent:string,reason:string,tools:string[]){db.prepare('INSERT INTO scope_decisions VALUES(?,?,?,?,?,?,?,?)').run(`SCOPE-${randomUUID()}`,conversationId,messageId,scope,intent,reason,JSON.stringify(tools),now());},
 recordReceipt(data:any){const id=`REC-${randomUUID()}`;db.prepare('INSERT INTO receipts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,data.conversationId,data.turnId,data.toolName,data.toolVersion,data.operationClass,hash(data.input),hash(data.result),JSON.stringify(data.evidence??[]),data.status,data.errorCode??null,data.durationMs,now());return id;},
 createArtifact(conversationId:string,type:string,payload:unknown,status='PROPOSED'){const id=`ART-${randomUUID().slice(0,8).toUpperCase()}`,t=now(),payloadHash=hash(payload);db.prepare('INSERT INTO artifacts VALUES(?,?,?,?,?,?,?,?,?)').run(id,conversationId,type,1,status,JSON.stringify(payload),payloadHash,t,t);return{id,version:1,type,status,payload,payloadHash};},
 getArtifact(id:string){const r=db.prepare('SELECT * FROM artifacts WHERE id=? ORDER BY version DESC LIMIT 1').get(id) as any;return r?{id:r.id,conversationId:r.conversation_id,type:r.type,version:r.version,status:r.status,payload:JSON.parse(r.payload),payloadHash:r.payload_hash}:undefined;},
 createAction(conversationId:string,artifact:any,principal:Principal,validationReceiptId:string,type='CREATE_RULE_DRAFT'){const id=`ACTION-${randomUUID().slice(0,8).toUpperCase()}`,expires=new Date(Date.now()+30*60_000).toISOString();db.prepare('INSERT INTO actions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,conversationId,type,artifact.id,artifact.version,artifact.payloadHash,'PROPOSED',expires,validationReceiptId,principal.userId,null,null,now(),null);return{id,type,artifactId:artifact.id,requiresConfirmation:true,expiresAt:expires,validationReceiptId};},
 getAction(id:string){return db.prepare('SELECT * FROM actions WHERE id=?').get(id) as any;},
 completeAction(id:string,key:string,result:unknown){db.prepare('UPDATE actions SET status=?,result=?,idempotency_key=?,executed_at=? WHERE id=?').run('SUCCEEDED',JSON.stringify(result),key,now(),id);},
 getActionByKey(key:string){return db.prepare('SELECT * FROM actions WHERE idempotency_key=?').get(key) as any;},
 saveOperation(id:string,conversationId:string,events:unknown[],response:unknown){db.prepare('INSERT INTO operations VALUES(?,?,?,?,?,?)').run(id,conversationId,JSON.stringify(events),JSON.stringify(response),'COMPLETED',now());},
 getOperation(id:string){const r=db.prepare('SELECT * FROM operations WHERE id=?').get(id) as any;return r?{...r,events:JSON.parse(r.events),response:JSON.parse(r.response)}:undefined;}
};
