import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { Evidence, Intent, OperationClass, Principal } from './domain.js';
import { repository } from './repository.js';
import { platform } from './adapters.js';

export interface ToolContext { principal:Principal;conversationId:string;turnId:string;intent:Intent;allowedOperation:OperationClass;abortSignal:AbortSignal; }
export interface ToolDefinition<I=unknown,O=unknown>{name:string;version:`${number}.${number}.${number}`;description:string;operationClass:OperationClass;inputSchema:z.ZodType<I>;outputSchema:z.ZodType<O>;timeoutMs:number;maximumModelResultBytes:number;owner:string;intents:Intent[];execute(ctx:ToolContext,input:I):Promise<{data:O;evidence:Evidence[];warnings?:{code:string;message:string}[]}>;}
const ev=(entityType:string,item:any,relationship:string,sourceSystem:string,label:string):Evidence=>({id:`EV-${entityType}-${item.id??item.ruleId??item.attributeId}-${item.version??item.ruleVersion??'current'}`,entityType,entityId:item.id??item.ruleId??item.attributeId,entityVersion:String(item.version??item.ruleVersion??item.sourceVersion??'current'),relationship,sourceSystem,label});
const search=z.object({query:z.string().min(1).max(50_000),limit:z.number().int().min(1).max(20).default(10)});
const readTool=(definition:Omit<ToolDefinition<any,any>,'version'|'operationClass'|'timeoutMs'|'maximumModelResultBytes'|'outputSchema'>):ToolDefinition<any,any>=>({...definition,version:'1.0.0',operationClass:'READ',timeoutMs:5000,maximumModelResultBytes:65536,outputSchema:z.any()});
const definitions:ToolDefinition<any,any>[]=[
 readTool({name:'searchDataDictionary',description:'Search authorized logical and physical data elements',inputSchema:search,owner:'Data Governance',intents:['DISCOVER_GLOSSARY','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.searchDataDictionary(i.query,i.limit,c.abortSignal);return{data,evidence:data.map(x=>ev('DATA_ELEMENT',x,'DICTIONARY_MATCH','Data Dictionary','Authoritative data-element metadata'))};}}),
 readTool({name:'getDatasource',description:'Retrieve datasource metadata',inputSchema:z.object({id:z.string()}),owner:'Data Governance',intents:['DISCOVER_GLOSSARY','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.getDatasource(i.id,c.abortSignal);return{data,evidence:data?[ev('DATASOURCE',data,'AUTHORITATIVE_DEFINITION','Data Dictionary','Datasource definition')]:[]};}}),
 readTool({name:'getNamespace',description:'Retrieve namespace metadata',inputSchema:z.object({id:z.string()}),owner:'Data Governance',intents:['DISCOVER_GLOSSARY','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.getNamespace(i.id,c.abortSignal);return{data,evidence:data?[ev('NAMESPACE',data,'AUTHORITATIVE_DEFINITION','Data Dictionary','Namespace definition')]:[]};}}),
 readTool({name:'searchGlossary',description:'Search authorized approved glossary attributes',inputSchema:search,owner:'Customer Data',intents:['DISCOVER_GLOSSARY','DISCOVER_RULES','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.searchGlossary(i.query,i.limit,c.abortSignal);return{data,evidence:data.map(x=>ev('GLOSSARY_ATTRIBUTE',x,'SEMANTIC_MATCH','Enterprise Glossary',x.usageStatus==='NEVER_USED'||x.usage==='NEVER_USED'?'Semantic match · never historically used':'Approved glossary record'))};}}),
 readTool({name:'searchRules',description:'Search approved CCRE rules',inputSchema:search,owner:'Decisioning',intents:['DISCOVER_RULES','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.searchRules(i.query,i.limit,c.abortSignal);return{data,evidence:data.map(x=>ev('RULE',x,'RECOMMENDATION_CANDIDATE','Rule Service','Approved rule definition'))};}}),
 readTool({name:'getRuleGraph',description:'Resolve version-pinned nested rule references and polarity',inputSchema:z.object({ruleId:z.string(),maxDepth:z.number().int().min(1).max(3).default(3)}),owner:'Decisioning',intents:['DISCOVER_RULES','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.getRuleGraph(i.ruleId,i.maxDepth,c.abortSignal);return{data,evidence:[ev('RULE',data.root??{id:i.ruleId},'RULE_GRAPH_ROOT','Rule Service','Version-pinned rule graph')]};}}),
 {...readTool({name:'findSimilarRules',description:'Find similar rules without claiming logical equivalence',inputSchema:search,owner:'Decisioning',intents:['DISCOVER_RULES','RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.findSimilarRules(i.query,i.limit,c.abortSignal);return{data,evidence:data.map(x=>ev('RULE',x,'SIMILARITY_CANDIDATE','Rule Similarity Service','Similarity evidence; not logical equivalence'))};}}),operationClass:'ANALYZE'},
 readTool({name:'findHistoricalContent',description:'Find approved historical content and associated rules',inputSchema:search,owner:'Content Operations',intents:['ANALYZE_CONTENT','RECOMMEND','PROPOSE_RULE','PROPOSE_TREATMENT'],async execute(c,i){const data=await platform.findHistoricalContent(i.query,i.limit,c.abortSignal);return{data,evidence:data.map(x=>ev('CONTENT',x,'HISTORICAL_ASSOCIATION','Content Service','Approved historical content-rule association'))};}}),
 {...readTool({name:'recommendRulesAndAttributes',description:'Rank authorized rule and glossary candidates',inputSchema:z.object({requirementText:z.string().max(10000),contentText:z.string().max(50000).default(''),topKRules:z.number().int().min(1).max(10).default(5),topKAttributes:z.number().int().min(1).max(20).default(10)}),owner:'Personalization ML',intents:['RECOMMEND','PROPOSE_RULE'],async execute(c,i){const data=await platform.recommend(i,c.abortSignal);return{data,evidence:[...(data.rules??[]).map((x:any)=>ev('RULE',x,'ML_CANDIDATE','Recommendation Service','Authorized ranked rule candidate')),...(data.attributes??[]).map((x:any)=>ev('GLOSSARY_ATTRIBUTE',x,'ML_CANDIDATE','Recommendation Service',x.usageStatus==='NEVER_USED'?'Semantic candidate · never historically used':'Historical and semantic candidate'))]};}}),operationClass:'ANALYZE',timeoutMs:10000},
 readTool({name:'getTreatmentMap',description:'Retrieve an authorized treatment map',inputSchema:z.object({id:z.string()}),owner:'Treatment Operations',intents:['PROPOSE_TREATMENT','EXPLAIN_DECISION'],async execute(c,i){const data=await platform.getTreatmentMap(i.id,c.abortSignal);return{data,evidence:data?[ev('TREATMENT_MAP',data,'AUTHORITATIVE_DEFINITION','Treatment Service','Treatment-map definition')]:[]};}})
];
const allowlists:Record<Intent,string[]>={DISCOVER_GLOSSARY:['searchDataDictionary','searchGlossary'],DISCOVER_RULES:['searchGlossary','searchRules','findSimilarRules'],ANALYZE_CONTENT:['searchGlossary','findHistoricalContent'],RECOMMEND:['searchDataDictionary','searchGlossary','searchRules','findSimilarRules','findHistoricalContent','recommendRulesAndAttributes'],EXPLAIN_DECISION:['searchRules','getTreatmentMap'],PROPOSE_RULE:['searchDataDictionary','searchGlossary','searchRules','findSimilarRules','findHistoricalContent','recommendRulesAndAttributes'],PROPOSE_TREATMENT:['searchRules','findHistoricalContent','getTreatmentMap']};
export class ToolRegistry{
 private tools=new Map<string,ToolDefinition<any,any>>();
 register(tool:ToolDefinition<any,any>){if(this.tools.has(tool.name))throw new Error(`Duplicate tool ${tool.name}`);if(!/^\d+\.\d+\.\d+$/.test(tool.version)||!tool.owner||tool.maximumModelResultBytes>65536)throw new Error(`Invalid descriptor ${tool.name}`);this.tools.set(tool.name,tool);}
 expose(intent:Intent){return(allowlists[intent]??[]).filter(n=>this.tools.has(n));}
 metadata(){return[...this.tools.values()].map(t=>({name:t.name,version:t.version,operationClass:t.operationClass,owner:t.owner,enabled:true}));}
 async invoke(name:string,raw:unknown,ctx:ToolContext){if(!this.expose(ctx.intent).includes(name))throw Object.assign(new Error('Tool is not allowed for this intent'),{code:'FORBIDDEN'});const tool=this.tools.get(name);if(!tool)throw Object.assign(new Error('Tool not found'),{code:'NOT_FOUND'});const input=tool.inputSchema.parse(raw),started=Date.now();let result:any,status='SUCCESS',errorCode:string|undefined;let timer:ReturnType<typeof setTimeout>|undefined;try{result=await Promise.race([tool.execute(ctx,input),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error('Tool timeout'),{code:'TIMEOUT'})),tool.timeoutMs);})]);tool.outputSchema.parse(result.data);}catch(e:any){status='ERROR';errorCode=e.code??'INTERNAL';result={data:null,evidence:[],warnings:[{code:errorCode,message:e.message??'The governed capability could not complete.'}]};}finally{if(timer)clearTimeout(timer);}const bytes=Buffer.byteLength(JSON.stringify(result.data));if(bytes>tool.maximumModelResultBytes){result.data={truncated:true,summary:'Result exceeded the configured model-context budget.'};result.warnings=[...(result.warnings??[]),{code:'TRUNCATED',message:'Result was compacted to its configured budget.'}];}const receiptId=repository.recordReceipt({conversationId:ctx.conversationId,turnId:ctx.turnId,toolName:name,toolVersion:tool.version,operationClass:tool.operationClass,input,result:result.data,evidence:result.evidence,status,errorCode,durationMs:Date.now()-started});return{status,data:result.data,evidence:result.evidence,warnings:result.warnings??[],metadata:{executionId:randomUUID(),toolName:name,toolVersion:tool.version,durationMs:Date.now()-started,truncated:bytes>tool.maximumModelResultBytes,receiptId}};}
}
export const registry=new ToolRegistry();definitions.forEach(x=>registry.register(x));
